# Project: attack
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe -D__DEBUG__
CC   = gcc.exe -D__DEBUG__
WINDRES = windres.exe
RES  = 
OBJ  = att_main.o $(RES)
LINKOBJ  = att_main.o $(RES)
LIBS =  -L"G:/Dev-Cpp/lib" -mwindows -lalleg_s -lgdi32 -lwinmm -lole32 -ldxguid -ldinput -lddraw -ldsound  -g3 
INCS =  -I"G:/Dev-Cpp/include" 
CXXINCS =  -I"G:/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"G:/Dev-Cpp/include/c++/3.4.2/backward"  -I"G:/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"G:/Dev-Cpp/include/c++/3.4.2"  -I"G:/Dev-Cpp/include" 
BIN  = attack.exe
CXXFLAGS = $(CXXINCS)   -g3
CFLAGS = $(INCS) -ALLEGRO_STATICLINK   -g3
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before attack.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "attack.exe" $(LIBS)

att_main.o: att_main.cpp
	$(CPP) -c att_main.cpp -o att_main.o $(CXXFLAGS)
